#!/bin/bash

STATE=mem
BATTCRITIC=2
BATTWARNING=5
ACDEVFILE=/sys/devices/pci0000:00/firmware_node/ACPI0003:00/power_supply/AC0/online

acplugged() {
	cat "$ACDEVFILE"
}

warning() {
	xmessage -center "WARNING: battery level is ${t}%"
}

suspend() {
	echo -n $STATE > /sys/power/state
}

getbattery() {
	enow=$(cat /sys/class/power_supply/BAT0/energy_now)
	efull=$(cat /sys/class/power_supply/BAT0/energy_full)
	vnow=$(cat /sys/class/power_supply/BAT0/voltage_now)

	r=$(echo "($enow * 100 / $vnow) * 100 / ($efull * 100 / $vnow)" |bc)
	echo $r
}

main() {
	[ $(acplugged) -eq 1 ] && exit
	t=$(getbattery)

	[ $t -lt $BATTCRITIC ] && suspend
	[ $t -lt $BATTWARNING ] && warning $t
}

main "$@"
