#!/bin/bash

STATE=mem
BATTCRITIC=3
BATTWARNING=8
ACPLUGGED="$(cat /sys/devices/pci0000:00/firmware_node/ACPI0003:00/power_supply/AC0/online)"
LIDSTATE="$(cat /proc/acpi/button/lid/LID/state |awk '{print $2}')"

warning() {
	xmessage -center "WARNING: battery level is ${t}%"
}

suspend() {
	echo -n $STATE > /sys/power/state
}

getbattery() {
	enow=$(cat /sys/class/power_supply/BAT0/energy_now)
	efull=$(cat /sys/class/power_supply/BAT0/energy_full)
	vnow=$(cat /sys/class/power_supply/BAT0/voltage_now)

	r=$(echo "($enow * 100 / $vnow) * 100 / ($efull * 100 / $vnow)" |bc)
	echo $r
}

main() {
	[ $LIDSTATE = "closed" ] && suspend
	[ $ACPLUGGED -eq 1 ] && exit

	t=$(getbattery)
	[ $t -le $BATTCRITIC ] && suspend
	[ $t -le $BATTWARNING ] && warning $t
}

main "$@"
