#!/bin/sh
# TODO: multisel

target="$1"
[ -z "$target" ] && target=.

while true; do
	sel="$(ls -1a "$target" |grep -v '^\.$' | dmenu -l 25)"
	ec=$?
	[ "$ec" -ne 0 ] && exit $ec

	c="$(echo "$sel" |cut -b1)"
	if [ "$c" = "/" ]; then
		newt="$sel"
	else
		newt="$(realpath "${target}/${sel}")"
	fi

	[ -e "$newt" ] && target="$newt"
	if [ ! -d "$target" ]; then
		mimeopen "$target"
		exit 0
	fi
done
