#!/bin/sh
# TODO: multisel

TARGET="$1"
[ -z "$TARGET" ] && TARGET=.

while true; do
	if [ ! -d "$TARGET" ]; then
		mimeopen "$TARGET"
		exit 0
	fi

	sel="$(ls -1a "$TARGET" |grep -v '^\.$' | dmenu -l 25)"
	ec=$?
	[ "$ec" -ne 0 ] && exit $ec
	TARGET="${TARGET}/${sel}"
done
