#!/bin/sh
# TODO: multisel

TARGET="$1"
[ -z "$TARGET" ] && TARGET=.

while true; do
	if [ ! -d "$TARGET" ]; then
		mimeopen "$TARGET"
		exit 0
	fi

	# skip non-existing files
	ne=true
	while "$ne"; do
		sel="$(ls -1a "$TARGET" |grep -v '^\.$' | dmenu -l 25)"
		ec=$?
		[ "$ec" -ne 0 ] && exit $ec
		[ -e "${TARGET}/${sel}" ] && ne=false
	done

	TARGET="${TARGET}/${sel}"
done
