#!/bin/bash

getbattery() {
	enow=$(cat /sys/class/power_supply/BAT0/energy_now)
	efull=$(cat /sys/class/power_supply/BAT0/energy_full)
	vnow=$(cat /sys/class/power_supply/BAT0/voltage_now)

	r=$(echo "($enow * 100 / $vnow) * 100 / ($efull * 100 / $vnow)" |bc)
	echo "${r}%"
}

getiwlink() {
	s=$(/sbin/iwconfig $1 |head -1 |tr -s " " '.' |cut -d'.' -f3)
	if [ "$s" != "off" ]; then
		r="$(/sbin/iwconfig $1 |grep Quality | sed 's/:\|=/./g' |tr -d [:alpha:],[:space:] |cut -d'.' -f2 |cut -d'/' -f1)%"
	else
		r="off"
	fi

	echo $r
}

getdate() {
	date +'%d/%m/%Y %H:%M'
}

getfreqs() {
	freqs=$(cat /sys/devices/system/cpu/*/cpufreq/scaling_cur_freq)
	ret=""
	for f in $freqs
	do
		f="$(echo "$f / 100000" |bc)"
		f=$(printf "0.%0.2d" $f)
		[ -z "$ret" ] && ret=$f || ret="${ret} $f"
	done

	echo $ret
}

gettemp() {
	t=$(cat /sys/class/hwmon/hwmon*/device/temp1_input)
	t=$(echo $t / 1000 |bc)
	r=$(printf "%d" $t)
	echo "${r}C"
}

getvol() {
	fds=$(amixer get Master |tail -1  |sed 's/.*\[\([^ ]*\)\] \[\([^ ]*\)\] \[\([^ ]*\)\].*/\1|\2|\3/')
	pct=$(echo $fds |cut -d'|' -f1)
	dcbl=$(echo $fds |cut -d'|' -f2)
	mute=$(echo $fds |cut -d'|' -f3)
	[ "$mute" = "on" ] && echo $pct || echo "${pct}*"
}

main() {
	battery=$(getbattery)
	iwlink=$(getiwlink wlan0)
	date=$(getdate)
	freqs=$(getfreqs)
	temp=$(gettemp)
	vol=$(getvol)
	printf "B:%s T:%s W:%s V:%-4s (%s) %s" "$battery" "$temp" "$iwlink" "$vol" "$freqs" "$date"
}

main "$@"
