#!/bin/bash
# Connects to a network
# Requires: wpa_supplicant, sdhcp, iwconfig

connect() {
	iface=$1
	essid=$2
	key=$3

	echo "Connecting to ${essid}..."

	ifconfig $iface up
	iwconfig $iface essid $essid

	if [ -n "$key" ]; then
		tmp=$(mktemp)
		echo "network={
			ssid=\"$essid\"
			psk=\"$key\"
			key_mgmt=WPA-EAP WPA-PSK
			proto=RSN WPA
			pairwise=CCMP TKIP
		}" >> $tmp
		wpa_supplicant -D nl80211 -i $iface -c "$tmp" -dd -B 2>&1 > /dev/null
		rm $tmp
	fi

	sdhcp -d $iface >/dev/null
}

die() {
	echo "$0: $@"
	exit 1
}

usage() {
echo -n "Usage: $0 [-hg] [-i <iface>] [-e <essid>] [-k <psk>] [-a <alias>]
-i <iface>	Network interface
-a <alias>	Use the specified alias to connect
-e <essid>	ESSID of the network to connect
-k <key>	Key of the network to connect
-f <file>	Networks file
-h		Show this helps
"
exit 1
}

main() {
	iface=wlan0
	file=~/.networks
	alias=
	essid=
	key=

	while getopts "ina:e:k:f:h" o; do
		case $o in
			i) iface=$OPTARG;;
			a) alias=$OPTARG;;
			e) essid=$OPTARG;;
			k) key=$OPTARG;;
			f) file=$OPTARG;;
			h) usage;;
		esac
	done

	[ "$(id -u)" -ne 0 ] && die "You must be root"
	[ -z "$alias" -a -z "$essid" ] && usage

	if [ -n "$alias" ]; then
		s="$(sed -n /^${alias}:/p $file |cut -d: -f2-3)"
		essid="$(echo $s |cut -d: -f1)"
		key="$(echo $s |cut -sd: -f2)"
	else
		# If explicitly specified, check if the ESSID do exists
		valid="$(iwlist wlan0 scan |grep ESSID |grep -wc $essid)"
		[ $valid -eq 0 ] && die "essid '$essid' is not valid"
	fi

	[ -z "$essid" ] && die "alias '${alias}' not found"

	apps=(wpa_supplicant sdhcp)
	for a in ${apps[@]}
	do
		pkill -f "$a"
	done

	connect "$iface" "$essid" "$key"
}

main "$@"
