#!/bin/bash

STATE=mem
BATTCRITIC=9
BATTWARNING=12
ACPLUGGED="$(cat $(du -a /sys/devices |grep 'AC0/online' |awk '{print $2}'))"
LIDSTATE="$(cat /proc/acpi/button/lid/LID/state |awk '{print $2}')"

export DISPLAY=:0
export XAUTHORITY=~/.Xauthority

warning() {
	pct="$1"
	L=" OK "

	xmessage -center -buttons "$L" -default "$L" "WARNING: battery level is ${pct}%" &

	for i in $(seq 3); do
		play -qn synth 00:00.05 sine $(echo "800 + (30 * $i)" |bc)
	done
}

suspend() {
	echo -n $STATE > /sys/power/state
}

getbattery() {
	enow=$(cat /sys/class/power_supply/BAT0/energy_now)
	efull=$(cat /sys/class/power_supply/BAT0/energy_full)
	vnow=$(cat /sys/class/power_supply/BAT0/voltage_now)

	r=$(echo "($enow * 100 / $vnow) * 100 / ($efull * 100 / $vnow)" |bc)
	echo $r
}

main() {
	[ $LIDSTATE = "closed" ] && suspend
	[ $ACPLUGGED -eq 1 ] && exit

	t=$(getbattery)
	if [ $t -le $BATTCRITIC ]; then
		suspend
	elif [ $t -le $BATTWARNING ]; then
		warning $t
	fi
}

main "$@"
