#!/bin/bash
# Connects to a network
# Requires: wpa_supplicant, dhclient and the iwconfig suite

NETWORKS_FILE=~/.networks

connect() {
	iface=$1
	essid=$2
	key=$3

	iwconfig $iface essid "$essid"
	if [ -n "$key" ]; then
		tmp=$(mktemp)
		echo -n "$key" | wpa_passphrase "$essid" >> $tmp
		wpa_supplicant -i $iface -c "$tmp" -B 2>&1 > /dev/null
		rm $tmp
	fi
	dhclient $iface >/dev/null &
	while [ -z "$gw" ]; do
		pkt="$(tcpdump -vlni $iface -c 1 -Q in udp 2>&1)"
		addr="$(echo "$pkt" |grep "Your-IP" |tr -d [:space:] |cut -b8-)"
		dgw="$(echo "$pkt" |grep "Gateway-IP" |tr -d [:space:] |cut -b11-)"
		egw="$(echo "$pkt" |grep "Default-Gateway" |tr -d [:space:] |cut -d: -f2)"
		[ -n "$dgw" ] && gw="$dgw" || gw="$egw"
	done
	ifconfig $iface $addr
	route add default gw $gw
}

die() {
	echo "$0: $@"
	exit 1
}

pickone() {
	iface="$1"
	file="$2"
	ids=$(iwlist "$iface" scan |grep ESSID |cut -d'"' -f2)
	nets=$(cat "$file")

	for net in $nets; do
		essid="$(echo "$net" |cut -d: -f2)"
		for id in $ids; do
			if [ "$id" = "$essid" ]; then
				echo "$essid"
				return
			fi
		done
	done
}

usage() {
echo -n "Usage: $0 [-hg] [-i <iface>] [-e <essid>] [-k <psk>] [-a <alias>]
-i <iface>	Network interface
-a <alias>	Use the specified alias to connect
-e <essid>	ESSID of the network to connect
-k <key>	Key of the network to connect
-f <file>	Networks file
-p 		Connect to a known network
-h		Show this help
"
exit 1
}

main() {
	iface=wlan0
	file="$NETWORKS_FILE"
	alias=
	essid=
	key=
	pick=0

	while getopts "inpa:e:k:f:h" o; do
		case $o in
			i) iface=$OPTARG;;
			a) alias=$OPTARG;;
			e) essid=$OPTARG;;
			k) key=$OPTARG;;
			f) file=$OPTARG;;
			p) pick=1;;
			h) usage;;
		esac
	done

	[ "$(id -u)" -ne 0 ] && die "You must be root"
	ifconfig $iface up 0.0.0.0
	if [ $pick -eq 1 ]; then
		echo "Looking for a suitable network... "
		essid="$(pickone "$iface" "$file")"
		[ -z "$essid" ] && die "no network found."
	fi
	[ -z "$alias" -a -z "$essid" ] && usage
	if [ -n "$alias" ]; then
		s="$(sed -n /^${alias}:/p $file |cut -d: -f2-3)"
		essid="$(echo $s |cut -d: -f1)"
		[ -z "$essid" ] && die "alias '${alias}' not found"
		key="$(echo $s |cut -sd: -f2)"
	else
		# Check the networks file to get a key
		key="$(sed -n /:${essid}:/p $file |cut -d: -f3)"
	fi

	echo "Connecting to ${essid}..."
	# If explicitly specified, check if the ESSID do exists
	valid="$(iwlist $iface scan |grep ESSID |grep -wc "$essid")"
	[ $valid -eq 0 ] && die "$essid: no network found"
	apps=(wpa_supplicant dhclient)
	for a in ${apps[@]}
	do
		pkill -f "$a"
	done
	connect "$iface" "$essid" "$key"
}

main "$@"
