#!/bin/sh

APIKEY="AIzaSyA5626nAOZTrgWtobeTGrFe0vFoEo9VBZg"
APIURI="https://www.googleapis.com/youtube/v3"
VIDURI="https://youtube.com/embed"
DEFLIST="RDEMWmz07MSPRGna5rHl5FWPRw"
PLAYER="mpv"
PLAYER_OPTS="-vo null --quiet"

ytapi() {
	cmd="$1"
	params="$2"
	wget -qO - "$APIURI/$cmd?key=$APIKEY&part=contentDetails&$params"
}

ytplrand() {
	listid="$1"
	maxres=50
	data="$(ytapi "playlists" "id=$listid")"
	nitems="$(echo "$data" |grep itemCount |cut -d: -f2)"
	choose="$(shuf -i 1-"$nitems" -n1)"
	page="$(echo "1 + ($choose - 1) / $maxres" |bc)"
	item="$(echo "$choose - (($page-1) * $maxres)" |bc)"
	pagetok=""

	# browse the pages until reach the item (that's the way YouTube works)
	for p in $(seq $page); do
		[ $p -gt 1 ] && pagetok="&pageToken=$(echo $data|grep nextPageToken |cut -d: -f2)"
		data="$(ytapi "playlistItems" "playlistId=$listid&maxResults=${maxres}${pagetok}")"
	done
	echo "$(echo "$data" |grep videoId |head -n $item |tail -1 |cut -d: -f2 |tr -cd "[:alnum:]_-")"
}

main() {
	listid="$1"
	[ -z "$listid" ] && listid="$DEFLIST"

	pgrep -a "$PLAYER" >/dev/null && exit 1
	rv=1
	while [ $rv -ne 0 ]; do
		songid="$(ytplrand "$listid")"
		"$PLAYER" $PLAYER_OPTS "$VIDURI/$songid"
		#rv=$?
		rv=0
	done
}

main "$@"
